{% set name = "daml" %}
{% set version = "0.55.0" %}
{% set sha256 = "48484f244104244d519487f047b7647ff243126679d37ca770e0d17b1dc33bb7" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core
    - poetry-dynamic-versioning

  run:
    - python >={{ python_min }},<3.12
    - hdbscan >=0.8.36
    - numpy >=1.24.2
    - pillow >=10.3.0
    - python-xxhash >=3.3
    - scipy >=1.10
    - scikit-learn >=1.2.1

test:
  imports:
    - daml
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/aria-ml/daml/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Data-Analysis Metrics Library

extra:
  recipe-maintainers:
    - aria-ml
